name: 'stored_proc_migration'
version: '1.0.0'
config-version: 2

profile: 'snowflake_demo'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
flags:
  require_generic_test_arguments_property: true

# Model configurations
models:
  stored_proc_migration:
    # Global settings
    +materialized: table
    +on_schema_change: fail
    
    # Staging models
    staging:
      +materialized: incremental
      +on_schema_change: fail
      +tags: ["staging", "snowflake_usage"]
      
    # Mart models  
    marts:
      +materialized: table
      +tags: ["mart", "snowflake_usage"]

# Seeds configuration
seeds:
  stored_proc_migration:
    +quote_columns: false

# Test configuration
tests:
  stored_proc_migration:
    +store_failures: true
